project:
  type: book

comments:
  hypothesis: true

book:
  title: 中文标题
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/haiiliin/quarto-tongji-thesis
  repo-actions: [edit, issue]
  downloads: [pdf, docx]
  output-file: tongji-thesis
  sidebar:
    search: true
  chapters:
    - index.md
    - chapters/chapter-1.md

# Bibliography
bibliography: bibliography.bib

# Language settings
lang: zh
reference-section-title: 参考文献
crossref:
  fig-title: 图
  tbl-title: 表
  fig-prefix: 图
  tbl-prefix: 表
  eq-prefix: 式

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    appendix-cite-as: display
    link-external-newwindow: true
  docx:
    output-file: tongji-thesis
  tongji-thesis-pdf:
    keep-tex: true
    output-file: tongji-thesis

    degree: doctor
    title: 中文标题
    etitle: English title
    headingtitle: 中文页眉标题

    author: 中文作者
    eauthor: English author
    studentnumber: 2000000

    abstract: |
      中文摘要。
    eabstract: |
      Abstract.

    keywords:
      - 中文关键词1
      - 中文关键词2
    ekeywords:
      - English keyword 1
      - English keyword 1

    emajorfirst: English major first
    cmajorfirst: 一级专业
    emajorsecond: English major second
    cmajorsecond: 二级专业

    edepartment: English department
    cdepartment: 院系

    esupervisor: English supervisor
    csupervisor: 导师
    eassosupervisor: English associate supervisor
    cassosupervisor: 副导师

    efunds: English funds
    cfunds: 基金

    denotation: |
      \begin{denotation}
        \item[ABBR] Full description
      \end{denotation}

    acknowledgement: 致谢
    resume: 简历
